server:
  port: 7001
  servlet:
    context-path: /uaa
spring:
  application:
    name: auth-service
  datasource:
    #type: com.mysql.cj.jdbc.MysqlDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.108.141.63:3306/u_auth?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: THTSS1000c
  redis:
    password:
    database: 0
    port: 6379
    host: 39.108.141.63
    timeout: 6000ms
  lettuce:
    pool:
      max-active: 10  #连接池最大连接数（使用负值表示没有限制）
      max-idle: 6   #连接池中的最大空闲连接
      min-idle: 2       # 连接池中的最小空闲连接
      max-wait: -1    # 连接池最大阻塞等待时间（使用负值表示没有限制）
  main:
    allow-bean-definition-overriding: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:5001/eureka/
logging:
  level:
    root: info
mybatis:
  mapper-locations: classpath:/mapper/*Dao.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
ribbon:
  eureka:
    enabled: true
